export function lineAt(doc: string, pos: number): { text: string; from: number } | null {
  const start = doc.lastIndexOf('\n', pos - 1) + 1;
  const end = doc.indexOf('\n', pos);
  const text = doc.slice(start, end < 0 ? doc.length : end);
  const lead = text.length - text.trimStart().length;
  const trimmed = text.trim();
  if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('//')) return null;
  return { text: trimmed, from: start + lead };
}

export const COMMANDS = (
  'APPEND BITCOUNT BITPOS BLPOP BRPOP COPY DBSIZE DECR DECRBY DEL DUMP ECHO EVAL EVALSHA EVAL_RO EXISTS EXPIRE EXPIREAT EXPIRETIME ' +
  'FLUSHDB GEOADD GEODIST GEOPOS GEOSEARCH GET GETDEL GETEX GETRANGE GETSET HDEL HEXISTS HGET HGETALL HINCRBY HINCRBYFLOAT ' +
  'HKEYS HLEN HMGET HRANDFIELD HSCAN HSET HSETNX HSTRLEN HVALS INCR INCRBY INCRBYFLOAT INFO KEYS LASTSAVE LINDEX LINSERT LLEN ' +
  'LMOVE LPOP LPOS LPUSH LPUSHX LRANGE LREM LSET LTRIM MEMORY MGET MSET MSETNX OBJECT PERSIST PEXPIRE PEXPIREAT PFADD PFCOUNT ' +
  'PFMERGE PING PSETEX PTTL PUBLISH RANDOMKEY RENAME RENAMENX RPOP RPUSH RPUSHX SADD SCAN SCARD SDIFF SDIFFSTORE SELECT SET ' +
  'SETEX SETNX SETRANGE SINTER SINTERCARD SINTERSTORE SISMEMBER SLOWLOG SMEMBERS SMISMEMBER SMOVE SPOP SRANDMEMBER SREM SSCAN ' +
  'STRLEN SUNION SUNIONSTORE TIME TOUCH TTL TYPE UNLINK XACK XADD XAUTOCLAIM XCLAIM XDEL XGROUP XINFO XLEN XPENDING XRANGE XREAD ' +
  'XREADGROUP XREVRANGE XTRIM ZADD ZCARD ZCOUNT ZDIFF ZINCRBY ZINTER ZLEXCOUNT ZMSCORE ZPOPMAX ZPOPMIN ZRANDMEMBER ZRANGE ' +
  'ZRANGEBYLEX ZRANGEBYSCORE ZRANK ZREM ZREMRANGEBYRANK ZREMRANGEBYSCORE ZREVRANGE ZREVRANK ZSCAN ZSCORE ZUNION ZUNIONSTORE ' +
  'CLIENT CONFIG COMMAND MULTI EXEC DISCARD WATCH UNWATCH FUNCTION FCALL FCALL_RO SCRIPT'
).split(' ');
