package postgres

import (
	"context"
	"database/sql"
	"strings"

	"github.com/relay-client/plugboard/apps/desktop/internal/db/sql/dialect"
	"github.com/relay-client/plugboard/apps/desktop/internal/model"
)

const relation = `format('%I.%I', $1::text, $2::text)::regclass`

var serials = map[string]string{"integer": "serial", "bigint": "bigserial", "smallint": "smallserial"}

func (d Dialect) tableDDL(ctx context.Context, db *sql.DB, obj model.DBObject, name string) (string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(ad.adbin, ad.adrelid),
		       a.attnotnull, a.attidentity::text, a.attgenerated::text,
		       COALESCE(pg_get_expr(ad.adbin, ad.adrelid) = 'nextval(' || quote_literal(pg_get_serial_sequence(`+relation+`::text, a.attname)::regclass::text) || '::regclass)', false)
		FROM pg_attribute a
		LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
		WHERE a.attrelid = `+relation+` AND a.attnum > 0 AND NOT a.attisdropped
		ORDER BY a.attnum`, obj.Schema, obj.Name)
	if err != nil {
		return "", dialect.NoRows(err, obj)
	}
	var lines []string
	for rows.Next() {
		var col, typ, identity, generated string
		var def sql.NullString
		var notNull, serial bool
		if err := rows.Scan(&col, &typ, &def, &notNull, &identity, &generated, &serial); err != nil {
			rows.Close()
			return "", err
		}
		if serial {
			if s, ok := serials[typ]; ok {
				lines = append(lines, "  "+d.QuoteIdent(col)+" "+s)
				continue
			}
		}
		line := "  " + d.QuoteIdent(col) + " " + typ
		switch {
		case generated == "s" && def.Valid:
			line += " GENERATED ALWAYS AS (" + def.String + ") STORED"
		case identity == "a":
			line += " GENERATED ALWAYS AS IDENTITY"
		case identity == "d":
			line += " GENERATED BY DEFAULT AS IDENTITY"
		case def.Valid:
			line += " DEFAULT " + def.String
		}
		if notNull {
			line += " NOT NULL"
		}
		lines = append(lines, line)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return "", err
	}
	if len(lines) == 0 {
		return "", dialect.Gone(obj)
	}
	constraints, err := dialect.QueryLines(ctx, db, `
		SELECT '  CONSTRAINT ' || quote_ident(conname) || ' ' || pg_get_constraintdef(oid, true)
		FROM pg_constraint WHERE conrelid = `+relation+` AND contype IN ('p', 'u', 'c', 'f', 'x')
		ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 WHEN 'f' THEN 3 ELSE 4 END, conname`, obj.Schema, obj.Name)
	if err != nil {
		return "", err
	}
	after, err := dialect.QueryLines(ctx, db, `
		SELECT pg_get_indexdef(i.indexrelid) || ';' FROM pg_index i
		WHERE i.indrelid = `+relation+` AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid)
		UNION ALL
		SELECT pg_get_triggerdef(t.oid, true) || ';' FROM pg_trigger t WHERE t.tgrelid = `+relation+` AND NOT t.tgisinternal
		UNION ALL
		SELECT 'COMMENT ON TABLE ' || $3 || ' IS ' || quote_literal(obj_description(`+relation+`, 'pg_class'))
		       || ';' WHERE obj_description(`+relation+`, 'pg_class') IS NOT NULL
		UNION ALL
		SELECT 'COMMENT ON COLUMN ' || $3 || '.' || quote_ident(a.attname) || ' IS ' || quote_literal(col_description(a.attrelid, a.attnum)) || ';'
		FROM pg_attribute a WHERE a.attrelid = `+relation+` AND a.attnum > 0 AND NOT a.attisdropped AND col_description(a.attrelid, a.attnum) IS NOT NULL`,
		obj.Schema, obj.Name, name)
	if err != nil {
		return "", err
	}
	out := "CREATE TABLE " + name + " (\n" + strings.Join(append(lines, constraints...), ",\n") + "\n);"
	if len(after) > 0 {
		out += "\n\n" + strings.Join(after, "\n")
	}
	return out, nil
}
